export const LABELS = {
  LOGIN: {
    LOGIN: 'Iniciar Sesión',
    USER: 'Usuario',
    USER_PLACEHOLDER: 'Ingresa tu usuario',
    PASSWORD: 'Contraseña',
    PASSWORD_PLACEHOLDER: 'Ingresa tu contraseña',
    MESSAGE: 'Recuerda no compartir estos datos',
    ERROR_MESSAGE: 'Revisa por favor si tus datos son correctos',
    WELCOME: 'Bienvenido al mejor banco'
  },
  PRODUCTS: {
    CDT: 'CDT',
    CREDIT_CARD: 'Tarjeta de Crédito',
    CURRENT_ACCOUNT: 'Cuenta corriente',
    SAVING_ACCOUNT: 'Cuenta de ahorros',
    C_HIP: 'Crédito Hipotecario',
    C_LIB: 'Crédito de Libranza',
    C_FREE: 'Crédito de Libre Destino',
  },
  DASHBOARD: {
    DETAIL: 'Ver detalle',
    NRO: 'Nro. ',
    PAY: 'Pagar',
    BEFORE_VERSION: 'Ir a la versión anterior',
    GOOD_MORNING: 'Buenos días, ',
    SHOW_OTHER_PRODUCTS: 'Mostrar otros productos',
    HOW_DO_YOUR_FINANCES_LOOK: '¿Cómo se ven tus finanzas?',
    IN_YOUR_SAVINGS_PRODUCTS_YOU_HAVE: 'En productos de ahorro tienes: ',
    PROFILE: 'Perfil',
    ALERTS: 'Alertas',
    EXIT: 'Salida segura',
    YOUR_PRODUCTS: 'TUS PRODUCTOS',
    YOUR_ORGANIZER: 'TU ORGANIZADOR',
    PAYMENTS: 'PAGOS',
    TRANSFERS: 'TRANSFERENCIAS',
    CERTIFICATES: 'CERTIFICADOS',
    SECURITY: 'SEGURIDAD',
    NOT_FIND: '¿No encuentras lo que estas buscando?',
    MESSAGE_1: 'Seguimos trabajando paratener todo lo que necesitas en esta nueva experiencia',
    MESSAGE_2: 'Mientras tanto puedes buscar lo que no encuentras en la versión anterior',
    OTHER_PRODUCT: '¿Quieres otro producto?',
    BUY_IT_HERE: 'Adquiérelo aquí.',
  },
  CARDS: {
    BALANCE: 'Saldo disponible: ',
    TOTAL_BALANCE: 'Saldo total: ',
    AVAILABLE_BALANCE: 'Cupo disponible: ',
    OVERDRAFT: 'En sobregiro: ',
    OVERDRAFT_DAYS: 'Días de sobregiro: ',
    INVESTED_VALUE: 'Valor invertido: ',
    NEXT_PAYMENT: 'Próximo pago: ',
    MIN_NEXT_PAYMENT: 'Próximo pago mínimo: ',
    TO_PAY: 'Te queda por pagar: ',
    IN_POCKETS: 'En bolsillos: ',
    TERM: 'Plazo: ',
    CUTOFF_DATE: 'Fecha de corte: ',
    DUE_DATE: 'Fecha de vencimiento: ',
    PAYMENT_DATE: 'Fecha de pago: ',
    YOU_HAVE_PAID: 'Has pagado: firstValue de secondValue cuotas',
  }
};
